<style>
    .cf_logo {
        height:22px;
        width:22px;
        margin-right:5px;
        float:left;
    }
    #cfCheckoutModal {
        max-width:400px;
    }
    .modal-dialog {
        max-width: 400px;
    }
    .modal-header {
        background-color: #672fd8;
    }
    .modal-body {
        margin-bottom:10px;
    }
    .modal-header, .close {
        color:#fff;
        opacity: 1;
    }
    .modal-header h3 {
        margin: 10px 0;
        font-size: 20px;
    }
    .modal-header p {
        font-size: 16px;
    }
    .modal-header .close {
        font-family: auto;
        line-height: 0px;
        text-decoration:none;
    }
    
    .modal-footer .cf_submit {
        background: #672fd8; 
    }
    .modal-footer .cf_submit:hover, .modal-footer .cf_submit:active {
        background: #672fd8;
    }
    .modal-footer {
        border-top:none;
    }
    #btn-cashfree {
        background: #672fd8;
    }
    /* .invalid class prevents CSS from automatically applying */
    .invalid input:required:invalid {
        background: #BE4C54;
        font-size: 1.2em;
        font-weight: 600;
    }

    /* Mark valid inputs during .invalid state */
    .invalid input:required:valid {
        background: #17D654;
    }
</style>

<!-- Add custom button on page/post -->
<div>
    <div>#cfButton#</div>
    <div id='response'>#txMsg#</div>
</div>

<!-- Modal for getting customer detail -->
<div class="modal fade" id="cfCheckoutModal" tabindex="-1" role="dialog" aria-labelledby="cfCheckoutModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form class="needs-validation" id="cfCheckoutForm" method="post" action="#redirectUrl#" novalidate>
                <div class="modal-header">
                    <a class="close" data-dismiss="modal">×</a>
                    <h3>
                        <img class="cf_logo" src="#icon#" />
                        <span>#title#</span>
                    </h3>
                    <p>#description#</p>
                    <h3>₹ #orderAmount#</h3>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label for="customerName">Name</label>
                        <input type="text" class="form-control" id="customerName" name="customerName" required>
                    </div>
                    <div class="form-group">
                        <label for="customerEmail" class="col-form-label">Email address</label>
                        <input type="email" class="form-control" id="customerEmail" aria-describedby="emailHelp" name="customerEmail" required>
                    </div>
                    <div class="form-group">
                        <label for="customerPhone">Phone Number</label>
                        <input type="text" class="form-control" id="customerPhone" name="customerPhone" required>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="hidden" class="form-control" id="pageID" name="pageID" value="#pageID#">
                    <button type="button" data-dismiss="modal" class="btn btn-default">Cancel</button>
                    <button type="submit" class="btn btn-primary cf_submit">Proceed</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
(function() {
    'use strict';
    window.addEventListener('load', function() {
      // Fetch all the forms we want to apply custom Bootstrap validation styles to
      var forms = document.getElementsByClassName('needs-validation');
      // Loop over them and prevent submission
      var validation = Array.prototype.filter.call(forms, function(form) {
        form.addEventListener('submit', function(event) {
          if (form.checkValidity() === false) {
            event.preventDefault();
            event.stopPropagation();
          }
          else{
            form.classList.add('was-validated');
          }
          
        }, false);
      });
    }, false);
  })();
</script>
