<style>
    /* .invalid class prevents CSS from automatically applying */
    .invalid input:required:invalid {
        background: #BE4C54;
        font-size: 1.2em;
        font-weight: 600;
    }

    /* Mark valid inputs during .invalid state */
    .invalid input:required:valid {
        background: #17D654;
    }
    .modal {
        display: none;
        position: fixed;
        z-index: 1;
        padding-top: 100px;
        left: 0;
        top: 0;
        height: 100%;
        overflow: auto;
        background-color: rgb(0,0,0);
        background-color: rgba(0,0,0,0.4);
    }
    .modal-content {
        background-color: #fefefe;
        margin: auto;
        width: 400px;
        max-width: 100%;
    }
    .close {
        color: #fff;
        float: right;
        font-size: 28px;
        font-weight: bold;
    }

    .close:hover,
    .close:focus {
        color: #000;
        text-decoration: none;
        cursor: pointer;
    }
    #cfCheckoutModal {
        width: 100% !important;
        max-width: 100% !important;
        margin-top: 0px !important;
        align-items: center;
        justify-content: center;
    }

    .modal-header {
        background-color: #672fd8;
        padding: 10px;
        color: #fff;
    }
    .modal-body {
        margin-bottom:10px;
    }
    .modal-header h3 {
        margin: 5px 0;
        font-size: 20px;
    }
    .modal-header p {
        font-size: 16px;
    }
    .modal-header .close {
        font-family: auto;
        line-height: 10px;
        text-decoration:none;
        color:#fff;
        opacity: 1;
    }
    .form-group {
        margin-top: 10px;
    }
    .form-modal label {
        margin-bottom: 5px;
        font-size: 15px;
        display: inline-block;
        font-weight: 500;
    }
    .form-modal input {
        width: -webkit-fill-available;
        padding: 3px;
        outline: unset;
        border: 1px solid #ccc;
        height: 30px;
        font-size: 16px;
    }
    .form-modal{
        padding: 20px;
    }
    .align-right-btns{
        text-align: right;
        margin-top: 20px;
    }
    .align-right-btns .cancel-btns{
        background-color: #fff;
        padding: 7px 10px;
        border: 1px solid #ccc;
        font-size: 14px;
        margin-right: 5px;
        color: #000;
    }
    .align-right-btns .proceed-btns{
        background-color: #672fd8;
        color: #fff;
        padding: 7px 10px;
        border: 1px solid #672fd8;
        font-size: 14px;
    }
    .cf_logo {
        height:22px;
        width:22px;
        margin-right:5px;
        float:left;
        vertical-align:middle;
    }
    .alert {
        padding: 10px;
    }
    .alert-success {
        color: #155724;
        background-color: #d4edda;
        border-color: #c3e6cb;
    }
    .alert-danger {
        color: #721c24;
        background-color: #f8d7da;
        border-color: #f5c6cb;
    }
    .alert-warning {
        color: #856404;
        background-color: #fff3cd;
        border-color: #ffeeba;
    }

    #cfCheckoutModal .modal-content{
        border-radius: 6px;
        overflow: hidden;
    }
    #cfCheckoutModal .cf_logo {
        position: absolute;
        left: 5px;
        top: 5px;
        border-radius: 4px;
        width: 50px;
        height: 50px;
    }
    #cfCheckoutModal .modal-header {
        background-color: #f4f7fb;
        padding: 10px;
        color: #444;
    }

    #cfCheckoutModal .modal-header p {
        font-size: 14px;
        color: #999;
        font-weight: 500;
    }



    #cfCheckoutModal input {
        padding: 5px !important;
        border-radius: 0.5rem;
        border: 2px solid #e3ebf6 !important;
        font-size: 18px !important;
        /* width: 96%; */
        display: block;
        height: 45px !important;
        background: #f4f7fb;
        margin: 10px auto;
        outline: none;
    }
    #cfCheckoutModal input:focus,
    #cfCheckoutModal input:active {
			border: 2px solid;
			background: #f4f7fb;
			box-shadow: none;
		}
       

/* CSS */
.button-5 {
  align-items: center;
  background-clip: padding-box;
  background-color: #fa6400  !important;
  border: 1px solid transparent;
  border-radius: .25rem;
  box-shadow: rgba(0, 0, 0, 0.02) 0 1px 3px 0;
  box-sizing: border-box;
  color: #fff !important;
  cursor: pointer;
  display: inline-flex;
  font-family: system-ui,-apple-system,system-ui,"Helvetica Neue",Helvetica,Arial,sans-serif;
  font-size: 16px;
  font-weight: 600;
  justify-content: center;
  line-height: 1.25;
  margin: 0;
  min-height: 3rem;
  padding: calc(.875rem - 1px) calc(1.5rem - 1px);
  position: relative;
  text-decoration: none;
  transition: all 250ms;
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
  vertical-align: baseline;
  width: auto;
}

.button-5:hover,
.button-5:focus {
  background-color: #fb8332;
  box-shadow: rgba(0, 0, 0, 0.1) 0 4px 12px;
}

.button-5:hover {
  transform: translateY(-1px);
}

.button-5:active {
  background-color: #c85000;
  box-shadow: rgba(0, 0, 0, .06) 0 2px 4px;
  transform: translateY(0);
}
 
/* CSS */
.button-6 {
  align-items: center;
  background-color: #FFFFFF  !important;
  border: 1px solid rgba(0, 0, 0, 0.1);
  border-radius: .25rem;
  box-shadow: rgba(0, 0, 0, 0.02) 0 1px 3px 0;
  box-sizing: border-box;
  color: rgba(0, 0, 0, 0.85)  !important;
  cursor: pointer;
  display: inline-flex;
  font-family: system-ui,-apple-system,system-ui,"Helvetica Neue",Helvetica,Arial,sans-serif;
  font-size: 16px;
  font-weight: 600;
  justify-content: center;
  line-height: 1.25;
  margin: 0;
  min-height: 3rem;
  padding: calc(.875rem - 1px) calc(1.5rem - 1px);
  position: relative;
  text-decoration: none;
  transition: all 250ms;
  user-select: none;
  -webkit-user-select: none;
  touch-action: manipulation;
  vertical-align: baseline;
  width: auto;
}

.button-6:hover,
.button-6:focus {
  border-color: rgba(0, 0, 0, 0.15);
  box-shadow: rgba(0, 0, 0, 0.1) 0 4px 12px;
  color: rgba(0, 0, 0, 0.65);
}

.button-6:hover {
  transform: translateY(-1px);
}

.button-6:active {
  background-color: #F0F0F1;
  border-color: rgba(0, 0, 0, 0.15);
  box-shadow: rgba(0, 0, 0, 0.06) 0 2px 4px;
  color: rgba(0, 0, 0, 0.65);
  transform: translateY(0);
}
</style>

<!-- Add custom button on page/post -->
<div>
    <div>#cfButton#</div>
    <div id='response'>#txMsg#</div>
</div>

<!-- Modal for getting customer detail -->
<div class="modal" id="cfCheckoutModal" tabindex="-1" role="dialog" aria-labelledby="cfCheckoutModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <a class="close close-btn" style="color: black;">×</a>
                <div style="    position: relative;padding-left: 70px;">
                    <img class="cf_logo" src="#icon#" alt="img"/>
                    <span>#title#</span>
                    <p>#description#</p>
                    <h3>₹ #orderAmount#</h3>
                </div>
                
            </div>
            <div class="form-modal" style="padding-top: 0px;">
                <form class="needs-validation" id="cfCheckoutForm" method="post" action="#redirectUrl#" novalidate>
                    <div class="form-group">
                        <label for="customerName">Name</label>
                        <input type="text" class="form-control" id="customerName" name="customerName" required>
                    </div>
                    <div class="form-group">
                        <label for="customerEmail">Email address</label>
                        <input type="email" class="form-control" id="customerEmail" aria-describedby="emailHelp" name="customerEmail" required>
                    </div>
                    <div class="form-group">
                        <label for="customerPhone">Phone Number</label>
                        <input type="text" class="form-control" id="customerPhone" name="customerPhone" required>
                    </div>
                    <div class="align-right-btns">
                        <button type="button" class="button-6 cancel-btns">CANCEL</button>
                        <button type="submit" class="button-5">PROCEED</button>
                        <input type="hidden" name="pageID" value="#pageID#">
                    </div>
                </form> 
            </div>
        </div>
    </div>
</div>

<script>
(function() {
    'use strict';
    window.addEventListener('load', function() {
      // Fetch all the forms we want to apply custom Bootstrap validation styles to
      var forms = document.getElementsByClassName('needs-validation');
      // Loop over them and prevent submission
      var validation = Array.prototype.filter.call(forms, function(form) {
        form.addEventListener('submit', function(event) {
          if (form.checkValidity() === false) {
            event.preventDefault();
            event.stopPropagation();
          }
          else{
            form.classList.add('was-validated');
          }
          
        }, false);
      });
    }, false);
  })();
</script>

<script>
    // Get the modal
    var modal = document.getElementById("cfCheckoutModal");
    // var modalDialog
    // Get the button that opens the modal
    var btn = document.getElementById("btn_cashfree");

    // Get the <span> element that closes the modal
    var span = document.getElementsByClassName("close-btn")[0];
    var cancel_btn = document.getElementsByClassName("cancel-btns")[0];
    // When the user clicks the button, open the modal 
    btn.onclick = function() {
    modal.style.display = "flex";
    }

    // When the user clicks on <span> (x), close the modal
    span.onclick = function() {
    modal.style.display = "none";
    }

    cancel_btn.onclick = function() {
        modal.style.display = "none";
    }
    // When the user clicks anywhere outside of the modal, close it
    window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
    }
</script>